sensor_setup: ['left_rgb', 'forward_rgb', 'right_rgb', 'rear_rgb', 'left_depth', 'forward_depth', 'right_depth', 'rear_depth', 'left_semantic', 'forward_semantic', 'right_semantic', 'rear_semantic']
habitat_data:
  metadata_path: '/data/home/joel/storage/objectnav/objectnav_hm3d_v1/val/val.json.gz'
  content_scenes: ["6s7QHgap2fW"]
  scenes_dir: "/data/home/joel/source/foundation_obj_nav/data/scene_datasets/"
