# @package _global_

defaults:
  - /habitat: habitat_config_base
  # - /habitat/task: objectnav
  - /habitat/task: pointnav
  - /habitat/task/lab_sensors:
    - gps_sensor
    - compass_sensor
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: semantic_agent
  # - /habitat/dataset/objectnav: hm3d
  - /habitat/dataset/pointnav: gibson
  - _self_

habitat:
  environment:
    max_episode_steps: 500
    iterator_options:
      shuffle: False
      cycle: False

  task:
    measurements:
      success:
        success_distance: 1.0

  simulator:
    turn_angle: 10
    agents:
      main_agent:
        sim_sensors:
          semantic_sensor:
            width: 640
            height: 480
            hfov: 90
            position: [0, 0.88, 0]
            orientation: [0, 0, 0]
        height: 0.88
        radius: 0.05
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
